[build]
  base = "."
  command = "npm install && npm run build"
  publish = "dist"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Assets folder should return 404 if files not found
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 