backend:
  name: github
  repo: francisco-the-man/web-stuff
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

# when using a custom domain, remove this line
site_url: https://francisco-the-man.github.io/web-stuff/
display_url: https://francisco-the-man.github.io/web-stuff/
logo_url: https://francisco-the-man.github.io/web-stuff/PIRATE-LOGO.png

# Optional: enables a staging workflow
publish_mode: editorial_workflow

media_folder: "public/projects/images"
public_folder: "/projects/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/_projects"
    create: true
    format: "json"
    extension: "json"
    delete: true
    slug: "{{fileName}}"
    identifier_field: fileName
    summary: "{{fileName}} - {{projectTitle}}"
    commit_message: "Update project: {{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "number", required: true}
      - {label: "File Name", name: "fileName", widget: "string", required: true}
      - {label: "Project Title", name: "projectTitle", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Project Image", name: "projectImg", widget: "image", required: true}
      - {label: "Type", name: "type", widget: "select", options: ["computational", "written"], required: true}
      - {label: "Category", name: "category", widget: "select", options: ["research", "computer", "both"], required: true}
      - {label: "Position", name: "position", widget: "select", options: ["left", "middle", "right"], required: true}
      - {label: "Repository Link", name: "repoLink", widget: "string", required: false} 