backend:
  name: git-gateway
  branch: main # Branch to update
  repo: francisco-the-man/web-stuff # Your GitHub repo
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

# when using a custom domain, remove this line
site_url: https://francisco-the-man.github.io/web-stuff/
display_url: https://francisco-the-man.github.io/web-stuff/
logo_url: https://francisco-the-man.github.io/web-stuff/PIRATE-LOGO.png

# Optional: enables a staging workflow
publish_mode: editorial_workflow

media_folder: "public/projects/images" # Media files will be stored in the repo
public_folder: "/projects/images" # The src attribute for uploaded media

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/projects
    label: "Project" # Used in the UI
    folder: "src/_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., project-name.md
    extension: "json"
    format: "json"
    fields: # The fields for each document
      - {label: "ID", name: "id", widget: "number", valueType: "int"}
      - {label: "File Name", name: "fileName", widget: "string"}
      - {label: "Project Title", name: "projectTitle", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Project Image", name: "projectImg", widget: "image"}
      - {label: "Type", name: "type", widget: "select", options: ["computational", "written"]}
      - {label: "Category", name: "category", widget: "select", options: ["computer", "research", "both"]}
      - {label: "Position", name: "position", widget: "select", options: ["left", "middle", "right"]}
      - {label: "Author Names", name: "authorNames", widget: "string", required: false}
      - {label: "Repository Link", name: "repoLink", widget: "string", required: false} 